[book]
authors = ["j4orz"]
language = "en"
src = "src"
title = "SITP"

[preprocessor.aquascope]

[preprocessor.katex]
after = ["links"]

[output.html]
additional-css = ["theme/css/custom.css"]
additional-js = ["theme/js/highlight-lean.min.js", "theme/js/custom.js"]
default-theme = "ayu"
preferred-dark-theme = "ayu"

[preprocessor.repl]
src = "https://comfy-daifuku-df4422.netlify.app/"
python.enable = true
python.loading = "lazy"
